version: '2'

services:

  elasticsearch:
    build:
      context: ./compose/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: ./compose/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./compose/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./compose/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./compose/filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/filebeat/filebeat.yml:/usr/share/kibana/config/filebeat.yml:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
