version: '2.2'

services:

  elasticsearch:
    build:
      context: ./compose/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
      interval: 10s
      timeout: 5s
      retries: 3

  logstash:
    build:
      context: ./compose/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./compose/logstash/conf.d:/usr/share/logstash/conf.d:ro
      - ./compose/logstash/patterns:/usr/share/logstash/patterns:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    build:
      context: ./compose/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601']
      interval: 10s
      timeout: 5s
      retries: 3

  filebeat:
    build:
      context: ./compose/filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/prod/nginx/:/var/log/prod/nginx/:ro
    ports:
      - "5066:5066"
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy

  apm-server:
    build:
      context: ./compose/apm-server/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./compose/apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    ports:
      - "8200:8200"
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

networks:

  elk:
    driver: bridge
