ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM elastic/elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# RUN elasticsearch-plugin install ingest-geoip
# RUN elasticsearch-plugin install ingest-user-agent
